# Generated by Django 2.1.9 on 2019-08-15 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SumDifference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('solution', models.IntegerField()),
                ('number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('occurrences', models.IntegerField(default=1)),
            ],
        ),
    ]
