site_name: calc
site_description: Challenge for Backstage
repo_url: https://github.com/chromano/backstage-test
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/chromano">chromano</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
